[package]
name = "alacritty"
version = "0.6.0-dev"
authors = ["Christian Duerr <contact@christianduerr.com>", "Joe Wilm <joe@jwilm.com>"]
license = "Apache-2.0"
description = "GPU-accelerated terminal emulator"
readme = "README.md"
homepage = "https://github.com/alacritty/alacritty"
edition = "2018"

[dependencies.alacritty_terminal]
path = "../alacritty_terminal"
version = "0.11.0-dev"
default-features = false

[dependencies]
clap = "2"
log = { version = "0.4", features = ["std"] }
time = "0.1.40"
fnv = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1"
glutin = { version = "0.24.0", features = ["serde"] }
notify = "4"
parking_lot = "0.10.2"
crossfont = { version = "0.1.0", features = ["force_system_fontconfig"] }
urlocator = "0.1.3"
copypasta = { version = "0.7.0", default-features = false }
libc = "0.2"
unicode-width = "0.1"

[build-dependencies]
gl_generator = "0.14.0"
rustc_tools_util = "0.2.0"

[target.'cfg(not(windows))'.dependencies]
xdg = "2"

[target.'cfg(not(target_os = "macos"))'.dependencies]
image = { version = "0.23.3", default-features = false, features = ["ico"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.2"

[target.'cfg(any(target_os = "macos", windows))'.dependencies]
dirs = "2.0.2"

[target.'cfg(not(any(target_os="windows", target_os="macos")))'.dependencies]
x11-dl = "2"
wayland-client = { version = "0.27.0", features = ["dlopen"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.7", features = ["impl-default", "wincon"]}

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.3"

[features]
default = ["wayland", "x11", "winpty"]
x11 = ["copypasta/x11"]
wayland = ["copypasta/wayland"]
winpty = ["alacritty_terminal/winpty"]
# Enabling this feature makes shaders automatically reload when changed
live-shader-reload = []
nightly = []
bench = []
