[package]
name = "alacritty"
version = "0.12.0-dev"
authors = ["Christian Duerr <contact@christianduerr.com>", "Joe Wilm <joe@jwilm.com>"]
license = "Apache-2.0"
description = "A fast, cross-platform, OpenGL terminal emulator"
readme = "README.md"
homepage = "https://github.com/alacritty/alacritty"
edition = "2021"
rust-version = "1.60.0"

[dependencies.alacritty_terminal]
path = "../alacritty_terminal"
version = "0.17.1-dev"
default-features = false

[dependencies.alacritty_config_derive]
path = "../alacritty_config_derive"
version = "0.2.1-dev"

[dependencies.alacritty_config]
path = "../alacritty_config"
version = "0.1.1-dev"

[dependencies]
clap = { version = "3.0.0", features = ["derive", "env"] }
log = { version = "0.4", features = ["std", "serde"] }
fnv = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1"
glutin = { version = "0.30.3", default-features = false, features = ["egl", "wgl"] }
winit = { version = "0.28.0", default-features = false, features = ["serde"] }
notify = "5.1.0"
parking_lot = "0.12.0"
crossfont = { version = "0.5.0", features = ["force_system_fontconfig"] }
copypasta = { version = "0.8.1", default-features = false }
raw-window-handle = "0.5.0"
libc = "0.2"
unicode-width = "0.1"
bitflags = "1"
dirs = "4.0.0"
once_cell = "1.12"

[build-dependencies]
gl_generator = "0.14.0"

[dev-dependencies]
clap_complete = "3.0.0"

[target.'cfg(not(windows))'.dependencies]
xdg = "2.4.0"

[target.'cfg(not(target_os = "macos"))'.dependencies]
png = { version = "0.17.5", default-features = false, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
raw-window-handle = "0.5.0"
cocoa = "0.24.0"
objc = "0.2.2"

[target.'cfg(not(any(target_os="windows", target_os="macos")))'.dependencies]
x11-dl = { version = "2", optional = true }
wayland-client = { version = "0.29.0", features = ["dlopen"], optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.36", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_Console",
    "Win32_Foundation",
]}

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.7.2"

[features]
default = ["wayland", "x11"]
x11 = [
    "copypasta/x11",
    "winit/x11",
    "glutin/x11",
    "glutin/glx",
    "x11-dl",
    "png"]
wayland = [
    "copypasta/wayland",
    "glutin/wayland",
    "winit/wayland",
    "winit/wayland-dlopen",
    "winit/wayland-csd-adwaita-crossfont",
    "wayland-client"]
nightly = []
