[package]
name = "font"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Font rendering using the best available solution per platform"
license = "Apache-2.0"

[dependencies]
euclid = "0.6.8"
libc = "0.2.11"
ffi-util = { path = "../ffi-util" }

[target.'cfg(not(target_os = "macos"))'.dependencies]
servo-fontconfig = { git = "https://github.com/jwilm/rust-fontconfig" }
freetype-rs = "0.9.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-text = "1.1.1"
core-foundation = "0.2.2"
core-graphics = "0.3.2"
core-foundation-sys = "0.2.2"
