[package]
name = "font"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Font rendering using the best available solution per platform"
license = "Apache-2.0"

[dependencies]
euclid = "0.12.0"
libc = "0.2"
foreign-types = "0.2.0"
log = "0.3"

[target.'cfg(not(target_os = "macos"))'.dependencies]
servo-fontconfig = { git = "https://github.com/jwilm/rust-fontconfig", branch = "updated-2017-10-8" }
freetype-rs = "0.13.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.3.0"
core-text = "6.1.0"
core-graphics = "0.8.1"
core-foundation-sys = "0.3.1"
