environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: nightly
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: stable
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: 1.24.1
  - TARGET: i686-pc-windows-msvc
    CHANNEL: nightly
  - TARGET: i686-pc-windows-gnu
    CHANNEL: nightly
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %CHANNEL% --default-host %TARGET%
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
